# Generated by Django 3.1.5 on 2021-01-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
