# Generated by Django 3.1.5 on 2021-01-30 20:25

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
